{
 "title": "Orchestrator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Numero de Jobs Procesados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "number_processed_groups", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo total de procesado",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_processing_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo promedio de procesado",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "avg_processing_time", "legendFormat": "__auto" }
   ]
  }
 ]
}