{
 "title": "DMP Application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of processed Groups by DMP Application",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_number_processed_groups",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "mysqlconnector_number_processed_groups",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sqlprocessor_number_processed_groups",
     "legendFormat": "{{pod}}"
    },
    { "expr": "regex_number_processed_groups", "legendFormat": "{{pod}}" },
    {
     "expr": "espublisher_number_processed_groups",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DMP Application Total Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "orchestrator_total_processing_time",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "mysqlconnector_total_processing_time",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sqlprocessor_total_processing_time",
     "legendFormat": "{{pod}}"
    },
    { "expr": "regex_total_processing_time", "legendFormat": "{{pod}}" },
    {
     "expr": "espublisher_total_processing_time",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DMP Application Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "orchestrator_avg_processing_time",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "mysqlconnector_avg_processing_time",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sqlprocessor_avg_processing_time",
     "legendFormat": "{{pod}}"
    },
    { "expr": "regex_avg_processing_time", "legendFormat": "{{pod}}" },
    {
     "expr": "espublisher_avg_processing_time",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}