apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: espublisher-metrics
  labels:
    app: espublisher
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: espublisher