apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlprocessor
  labels:
    app: sql-proc
spec:
  replicas: {{ .Values.sqlprocessor.replicas }}
  selector:
    matchLabels:
      app: sql-proc
  template:
    metadata:
      labels:
        app: sql-proc
    spec:
      containers:
      - name: sqlprocessor
        image: deansf/sqlprocessor
        ports:
          - name: metrics
            containerPort: 6941
        env:
          - name: "ELASTICHOST"
            value: {{ .Values.general.elastichost }}
          - name: "ELASTICPORT"
            value: {{ .Values.general.elasticport }}
          - name: "ELASTICUSER"
            value: {{ .Values.general.elasticuser }}
          - name: "ELASTICPASS"
            valueFrom:
              secretKeyRef:
                name: databases-elasticsearch
                key: elasticsearch-password
                optional: false
          - name: "RABBITHOST"
            value: {{ .Values.general.rabbithost }}
          - name: "RABBITPORT"
            value: {{ .Values.general.rabbitport }}
          - name: "RABBITUSER"
            value: {{ .Values.general.rabbituser }}
          - name: "RABBITPASS"
            valueFrom:
              secretKeyRef:
                name: monitoring-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: "RABBITCONSUMEQUEUE"
            value: {{ .Values.mysqlconnector.rabbitqueuename }}
          - name: "RABBITPUBLISHQUEUE"
            value: {{ .Values.sqlprocessor.rabbitqueuename }}
          - name: "MARIADBNAME"
            value: {{ .Values.general.mariadbname }}
          - name: "MARIADBHOST"
            value: {{ .Values.general.mariadbhost }}
          - name: "MARIADBPORT"
            value: {{ .Values.general.mariadbport }}
          - name: "MARIADBUSER"
            value: {{ .Values.general.mariadbuser }}
          - name: "MARIADBPASS"
            valueFrom:
              secretKeyRef:
                name: databases-mariadb
                key: mariadb-root-password
                optional: false
          