from elasticsearch import Elasticsearch
import urllib3
urllib3.disable_warnings()

#Para conectar el puerto de Elasticsearch, ponerlo en consola y asegurar que elastic se este ejecutando--
#kubectl port-forward quickstart-es-default-0 9200:9200

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "4949QwH1tyM37hL8owoD3e2p" #puede cambiar si se desinstala

# Crea la instancia de un cliente
es = Elasticsearch(['https://localhost:9200'],basic_auth=('elastic',ELASTIC_PASSWORD),verify_certs=False)

#////////////////////CREAR UN INDICE
 # Crea un indice o bien le mete datos a ese indice
data = {"title": "Base de datos 2", "Porcentaje": "100"}
result = es.indices.create(index='jobs', ignore = 400)
#result2 = es.create(index="pamela",id=2,body=data)
print("-----------------------------------")
print(result)
print("-----------------------------------")

#///////////////////CONSULTAR UN INDiCE ESPECIFICO todo EL BODY
resp = es.get(index="materias", id=1)
print("-----------------------------------")
print(resp['_source'])
print("-----------------------------------")

# #//////////////////MODIFICAR CON RESPECTO A UN ID, pero si no existe lo crea
data = {"title": "MODY 2", "Porcentaje": "100"}
result = es.index(index='jobs', id=2,body=data)
#result2 = es.create(index="pamela",id=2,body=data)
print("-----------------------------------")
print(result)
print("-----------------------------------")

# #/////////////////Eliminar un indice
result = es.indices.delete(index="jobs",ignore=400)
print("-----------------------------------")
print(result)
print("-----------------------------------")

#---Datos elimina, de un indice. Se le indica el id especifico
result = es.delete(index="jobs",id=1)
print("-----------------------------------")
print(result)
print("-----------------------------------")
