apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlconnector
  labels:
    app: MySQL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MySQL
  template:
    metadata:
      labels:
        app: MySQL
    spec:
      containers:
      - name: mysqlconnector
        image: pamlez/mysql_demo
        env:
          - name: "ELASTICHOST"
            value: {{ .Values.general.elastichost }}
          - name: "ELASTICPORT"
            value: {{ .Values.general.elasticport }}
          - name: "ELASTICUSER"
            value: {{ .Values.general.elasticuser }}
          - name: "ELASTICPASS"
            valueFrom:
              secretKeyRef:
                name: databases-elasticsearch
                key: elasticsearch-password
                optional: false
          - name: "RABBITHOST"
            value: {{ .Values.general.rabbithost }}
          - name: "RABBITPORT"
            value: {{ .Values.general.rabbitport }}
          - name: "RABBITUSER"
            value: {{ .Values.general.rabbituser }}
          - name: "RABBITPASS"
            valueFrom:
              secretKeyRef:
                name: monitoring-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: "RABBITQUEUENAME"
            value: {{ .Values.general.rabbitqueueP }}
          - name: "RABBITQUEUEMySQL"
            value: {{ .Values.general.rabbitqueueMySQL }}
          - name: "MARIADBNAME"
            value: {{ .Values.general.mariadbname }}
          - name: "MARIADBHOST"
            value: {{ .Values.general.mariadbhost }}
          - name: "MARIADBPORT"
            value: {{ .Values.general.mariadbport }}
          - name: "MARIADBUSER"
            value: {{ .Values.general.mariadbuser }}
          - name: "MARIADBPASS"
            valueFrom:
              secretKeyRef:
                name: databases-mariadb
                key: mariadb-root-password
                optional: false