enableGrafana : False
enablePrometheus : False
enableRabbit : true

rabbitmq:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
  service: 
    type: NodePort
    nodePorts:
      amqp: 30100
      manager: 30150

kube-prometheus:
  fullnameOverride: "main"

grafana:
  datasources:
    secretDefinition:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://main-prometheus:9090/
        access: proxy
        isDefault: true
  admin:
    password: "11111111"