enableElastic : true
enableMaria : true

elasticsearch:
  global:
    kibanaEnabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Nodos master Elastic
  master:
    replicaCount: 1
    resources:
      limits: 
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 128Mi
    heapSize: 128m

  # Nodos de datos Elastic
  data:
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 25m
        memory: 256Mi
    heapSize: 384m
  
  # Nodos de Coordinación Elastic
  coordinating:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 128Mi
    heapSize: 128m

  # Nodos de ingest Elastic
  ingest:
    enabled: false
    replicaCount: 2
    resources:
      limits:
        cpu: 25m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi
    heapSize: 128m

mariadb:
  architecture: replication

  # Nodo primario
  primary:
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
      

  # Nodos secundarios
  secondary:  
    replicaCount: 2
    resources:
      limits:
        cpu: "1000m"
        memory: "512Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"

  metrics: 
    enabled: true
    serviceMonitor: 
      enabled: true