apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearchpublisher
  labels:
    app: espublisher
spec:
  replicas: {{ .Values.espublisher.replicas }}
  selector:
    matchLabels:
      app: espublisher
  template:
    metadata:
      labels:
        app: espublisher
    spec:
      containers:
      - name: elasticsearchpublisher
        image: ihuskyx/espublisher
        env:
          - name: "ELASTICHOST"
            value: {{ .Values.general.elastichost }}
          - name: "ELASTICPORT"
            value: {{ .Values.general.elasticport | quote }}
          - name: "ELASTICUSER"
            value: {{ .Values.general.elasticuser }}
          - name: "ELASTICPASS"
            valueFrom:
              secretKeyRef:
                name: databases-elasticsearch
                key: elasticsearch-password
                optional: false
          - name: "RABBITHOST"
            value: {{ .Values.general.rabbithost }}
          - name: "RABBITPORT"
            value: {{ .Values.general.rabbitport | quote }}
          - name: "RABBITUSER"
            value: {{ .Values.general.rabbituser }}
          - name: "RABBITPASS"
            valueFrom:
              secretKeyRef:
                name: monitoring-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: "RABBITQUEUENAME"
            value: {{ .Values.regexprocessor.rabbitqueuename }}